- name: check src exists
  stat:
    path: "{{vim_conf_cloned_dest}}/{{item}}"
  register: st
- name: Make symbolic links
  file:
    src: "{{vim_conf_cloned_dest}}/{{item}}"
    dest: "{{ansible_env.HOME}}/{{item}}"
    state: link
  when: st.stat.exists
