---
- name: Check src file
  stat:
    path: "{{ghq_root.stdout}}/github.com/{{remote_repository_path}}/{{item}}"
  register: st_src
- name: Check dest file
  stat:
    path: "{{ansible_env.HOME}}/{{item}}"
  register: st_dest
- block:
  - name: Back up existing file
    shell: "mv {{ansible_env.HOME}}/{{item}} {{ansible_env.HOME}}/{{item}}.{{vim_conf_datetime}}"
    when: st_dest.stat.exists and not st_dest.stat.islnk
  - name: Make symbolic links
    file:
      src: "{{ghq_root.stdout}}/github.com/{{remote_repository_path}}/{{item}}"
      dest: "{{ansible_env.HOME}}/{{item}}"
      state: link
      force: yes
  when: st_src.stat.exists or vim_conf_force
