---
# tasks file for vim-conf
- name: ghq root
  shell: /home/vagrant/.go/bin/ghq root
  register: ghq_root
  changed_when: false
- name: mkdir .vimundo
  file:
    path: "{{ansible_env.HOME}}/.vimundo"
    state: directory
- name: Clone the vim config repository
  ghq:
    name: "{{remote_repository_path}}"
    executable: "{{vim_conf_ghq_executable}}"
- include: create_link.yml
  with_items:
  - .vim
  - .vimrc
