---
# tasks file for vim-conf
- name: mkdir .vimundo
  file:
    path: "{{ansible_env.HOME}}/.vimundo"
    state: directory
- name: Clone the vim config repository
  ghq:
    name: "{{remote_repository_path}}"
    executable: "{{ghq_executable}}"
- name: ghq root
  shell: "{{ansible_env.HOME}}/.go/bin/ghq root"
  register: ghq_root
  changed_when: false
- include: create_link.yml
  with_items:
  - .vim
  - .vimrc
