---
# tasks file for vim-conf
- name: ghq root
  shell: /home/vagrant/.go/bin/ghq root
  register: ghq_root
  changed_when: false
- name: mkdir .vimundo
  file:
    path: "{{ansible_env.HOME}}/.vimundo"
    state: directory
- name: Clone vim.conf
  ghq:
    name: "{{remote_repository_path}}"
    executable: "{{vim_conf_ghq_executable}}"
- name: Make symbolic links
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  with_items:
  - src: "{{ghq_root.stdout}}/github.com/{{remote_repository_path}}/.vim"
    dest: "{{ansible_env.HOME}}/.vim"
  - src: "{{ghq_root.stdout}}/github.com/{{remote_repository_path}}/.vimrc"
    dest: "{{ansible_env.HOME}}/.vimrc"
